### ISSUE TITLE
Refactor Credentials use and other common utilities

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/toolkit#17]
We should consider a mechanism to share 'classes' & util methods between packages:

* Credentials (username / apiKey) + several related properties (and some operations) are being used in several packages (eg. sql & maps).

* encoding params in URLs and so on?

* GET or POST depending on size?

**Comment by rjimenezda** [comment]
The only way of doing this is creating a public package on the repo. Having a common folder outside all projects won't work[1]. So, we could use this ticket to define a list of things we want to see there.

It probably won't make a lot of sense as an individual package, but :man_shrugging: 

[1] The reason for this is you cannot have source code outside of `rootDir` on typescript.

**Comment by VictorVelarde** [comment]
Done per core (WIP) package
