### ISSUE TITLE
Platform package

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/toolkit#24]
Right now, the auth package has a small class that fetches the basic userinfo (API v4 `/me`) for you, since the URL is part of the OAuth response. I think that's fine, but it makes the App / OAuthApp split weird, since only OAuthApps have that information.

At some point we'll need to get that information for all Apps, not just OAuth apps, and more information of the platform (list datasets, for instance). I think we should move this to its own package.

**Comment by VictorVelarde** [comment]
I aggree, we should consider these new packages.

**Comment by VictorVelarde** [comment]
We might eventually move some logic out from toolkit (OAuthapp) and back into the auth package itself, leaving the toolkit for other general 'aggregations'. In the meantime, I'm gonna postpone creating more packages
