### ISSUE TITLE
[SQL] Improve error handling

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/toolkit#30]
Right now, rate limits are handled gracefully. However, we should also be wary of:

- 503 errors, that might happen if the SQL API is not ready for whatever reason and nginx can't redirect the request to it. We should just retry after some time (maybe immediately)
- Timeout errors, these might come back as a 429, but probably don't have the retry headers. To try this, PG_Sleep is probably the way.

**Comment by jesusbotella** [comment]
Do we have any retry limit? I think that if we retry 503 errors right away we're gonna end up in a loop.

**Comment by jesusbotella** [comment]
Merged!
