### ISSUE TITLE
[toolkit / kepler.gl] Identify API calls from app client (Kepler.gl)

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/toolkit#40]
See: https://github.com/CartoDB/product/issues/467#issuecomment-539905698

After some research and conversations, a plan has been set on **https://app.clubhouse.io/cartoteam/epic/57961/api-and-client-metrics** with different steps:

- [x] Adding headers to SQL API https://github.com/CartoDB/CartoDB-SQL-API/pull/640
- [x] Implementing events on custom-storage #56 
- [x] Check with Back 
- [x] Allow to distinguish between kepler.gl web app & dashboard

**Comment by neokore** [comment]
Applied in Dashboard. Kepler.gl will follow.

**Comment by VictorVelarde** [comment]
Great, let's close this when rc-17 is on prod on kepler.gl side

**Comment by neokore** [comment]
Uber merged my PR and this is now live on prod on Kepler.gl!!
