### ISSUE TITLE
Review visualization model from cartodb and add missing fields

### ISSUE THREAD

**Issue by jesusbotella** [CartoDB/toolkit#41]
As we're kinda building a visualization model ourselves, it would be good to mimick visualization model from cartodb so that we have as little properties mismatching as possible.

One of these can be a `tags` property that we definitely need to include.

**Comment by VictorVelarde** [comment]
Please @csubira add a list here of the properties, the job you did for kuviz will be useful here too!

**Comment by VictorVelarde** [comment]
@jesusbotella @csubira I think we have almost every relevant property on the kepler.gl side, but I would like to know about the **tags** thing.

With visualizations (including kuviz) Is it a many to many table, shared among datasets and maps?. I'm wondering how it could be managed  from the CustomStorage side (if it is not a big 'melón')

**Comment by jesusbotella** [comment]
Here are visualization field from public visualization presenter:
```
id:               @visualization.id,
name:             @visualization.name,
display_name:     @visualization.display_name,
attributions:     @visualization.attributions,
source:           @visualization.source,
license:          @visualization.license,
type:             @visualization.type,
tags:             @visualization.tags,
description:      @visualization.description,
created_at:       @visualization.created_at,
updated_at:       @visualization.updated_at,
title:            @visualization.title,
kind:             @visualization.kind,
privacy:          @visualization.privacy.upcase,
```

I guess that fields like attributions, license, or source are not relevant for Kepler's visualizations, so tags field is the only that I guess we should add to our Kepler visualizations' table.

I thought of adding a JSON field to our visualizations' table, but we wouldn't be able to search visualizations with a certain tag from a SQL query with that approach.

Creating a Tags table to link tags to visualizations would be the best option, but we'll be mimicking cartodb functionality in our custom storage as we've done with more things already. I'm starting to think it'd have been better to use kuviz api to create our visualizations, as we already use COPY to upload our datasets.

**Comment by VictorVelarde** [comment]
Ok, I see. I agree that tags is probably the most relevant, because it would allow a better Search in the Dashboard (in the future...)

For tags, I think that a JSON field could still provide some searching (like in the example here: https://www.postgresql.org/docs/9.4/datatype-json.html), but a tags table would probably be better, yes. 

Regarding to using kuviz API, doesn't it imply that we would just manage HTML? If that's the case, it would be less powerful than our current CustomStorage approach, including the full `config` of the kepler viz, with 'editable' styles.

So my proposal would be going after the Tag table + a Vis to Tags n to n relation table, how do you see it @jesusbotella  @neokore ?

**Comment by jesusbotella** [comment]
The easiest way to do this is JSON, for sure, but I guess that the table approach is more flexible as I said :) So that would be my preferred approach.

What I meant with the kuviz API is that given that we have a [custom visualizations controller](https://github.com/CartoDB/cartodb/blob/master/app/controllers/carto/api/public/custom_visualizations_controller.rb) to create cartodb visualizations for kuviz (kinda similar to ours apart from the parameters you talked about which could be JSON parameters within the table) we could've had something similar to save Kepler's visualizations, making the process easier and more compatible with our current dashboard.

**Comment by VictorVelarde** [comment]
OK. 

After your comments I think we should not add tags now. Let's go with what we currently have for CustomStorage. 

And later on we can try to make a bit more of research and that other approach; maybe a new package to manage kuvizs, properly integrated with the app, would be eventually the best option.

**Comment by jesusbotella** [comment]
Do we close this issue then? :)

**Comment by VictorVelarde** [comment]
Still not the moment to add tags, closing by now.
