### ISSUE TITLE
[customStorage] Issues on updating and deleting visualizations

### ISSUE THREAD

**Issue by neokore** [CartoDB/toolkit#52]
- [x] Fix repeated `datasets_vis` entries when saving an existing visualization
- [x] Review deleting old datasets when saving an existing visualizations

~- [ ] Allow configure retry management in requests queue (set max retries value)~

**Comment by VictorVelarde** [comment]
Let's split this up, keeping bux fixing on tables separated from improvements.

**Comment by VictorVelarde** [comment]
I guess this should be closed now, @neokore. Feel free to reopen if needed
