### ISSUE TITLE
Weird behavior for lines and points with high size

### ISSUE THREAD

**Issue by manmorjim** [CartoDB/toolkit#85]
There is a weird behavior with points with high radius:
![image](https://user-images.githubusercontent.com/1272750/80498369-ee418a00-896b-11ea-9ff2-9e04cada2e56.png)

And the same with lines with high line width:
![image](https://user-images.githubusercontent.com/1272750/80498391-f4d00180-896b-11ea-9de6-bcdd84cc83fe.png)

They seem to be affected by clipping extension. It is required for polygons in order to avoid artifacts and it was added by uber people for MVTLayers: https://github.com/visgl/deck.gl/pull/4336

An suggestion would be removing it for lines and points layers.

**Comment by VictorVelarde** [comment]
@manmorjim I would suggest creating an issue at deck.gl repo upstream, related to the pure MVTLayer to see if we can get some feedback from clip extension developers. 

Then we can decide if work has to be done in deck.gl itself or our side on toolkit

**Comment by manmorjim** [comment]
Issue created: https://github.com/visgl/deck.gl/issues/4549

**Comment by manmorjim** [comment]
Fixed in https://github.com/visgl/deck.gl/pull/4557
