### ISSUE TITLE
Dynamic raidus scale for points size based on pixels

### ISSUE THREAD

**Issue by manmorjim** [CartoDB/toolkit#86]
The radius size for points is based on distances (meters/degrees) rather than pixels so they are adapted depending on the zoom level:

![Peek 2020-04-28 16-46](https://user-images.githubusercontent.com/1272750/80501649-f996b480-896f-11ea-87ff-142873eee073.gif)

It is desirable to have radius size based on pixels since this is the most common form of representation for points. By this way, they are still visible in low zoom levels by keeping their size.

For lines there is a property called [`lineWidthUnits` ](https://deck.gl/#/documentation/deckgl-api-reference/layers/geojson-layer?section=properties) which accepts the value `'pixels'`. 

Unfortunately this options is not available for points so a workaround would be using dynamic `radiusScale` like is described in https://github.com/visgl/deck.gl/issues/1259#issuecomment-352938186

Something like setting `radiusScale` as pixel per meters multiplying factor that you can get from the viewport. This has to be updated everytime the zoom changes: https://github.com/visgl/deck.gl/blob/master/modules/core/src/viewports/viewport.js#L92

**Comment by VictorVelarde** [comment]
@manmorjim I think we should try to move this discussion to clubhouse (perhaps creating a new story linked to SizeBinsStyle helper one... just copy this 🔝 content as it is), leaving GH just for the linked PRs.

If you do that, please share the story number with me and then we can close this issue

**Comment by manmorjim** [comment]
done! moved to 72601

**Comment by VictorVelarde** [comment]
Thx
